'use client';

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from '@/components'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>
          <div className="flex flex-col bg-[#5757574d] backdrop-blur-2xl min-h-screen">
            <Header />
            {children}

            <footer>
              <p className="text-lm text-white w-full text-center py-5 px-2">By Nandier Ruiz</p>
            </footer>
          </div>

      </body>
    </html>
  )
}
